server:
  port: 8082

spring:
  data:
    mongodb:
      database: MobileService
      host: localhost
      port: 27017
  application:
    name: mobile-service


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka