server:
  port: 8081

spring:
  data:
    mongodb:
      database: RatingService
      host: localhost
      port: 27017
  application:
    name: rating-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
